services:
  app:
    build: .
    volumes:
      - ./data:/workspace/data
      - ./logs:/workspace/logs
      - ./output:/workspace/output
    working_dir: /workspace
    environment:
      NH4_API_KEY: ${NH4_API_KEY}
      DH3_API_KEY: ${DH3_API_KEY}
      GOOGLE_GEOCODING_API_KEY: ${GOOGLE_GEOCODING_API_KEY}

    stdin_open: true
    tty: true
